### ISSUE TITLE
Open Page Screenshot by default

### ISSUE THREAD

**Issue by haalogen** [gemini-testing/html-reporter#336]
Hi,

I've upgarded "html-reporter" from "4.6.2" to "5.16.4".
How can I have Page Screenshot opened by default in report?
It was very convenient before.

**Comment by DudaGod** [comment]
Hello.

You are talking about screenshot that is taken when the test falls? Currently there is no way to control this behaviour but you can send PR to add ability to open/close it by default. We changed it on this PR - https://github.com/gemini-testing/html-reporter/pull/232 because screenshots on test fail usually takes a lot of space.

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue. Thank you.
